name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image app
        run: docker build -t jrodga1604/react-test -f ./client/Dockerfile.dev ./client

#////////////``

      - name: Run tests
        run: docker run -e CI=true jrodga1604/react-test npm test

      - name: build client cointainer
        run: docker build -t jrodga1604/multi-client ./client
      
      - name: build nginx cointainer
        run: docker build -t jrodga1604/multi-nginx ./nginx
      
      - name: build server cointainer
        run: docker build -t jrodga1604/multi-server ./server
      
      - name: build worker cointainer
        run: docker build -t jrodga1604/multi-worker ./worker

# //////////////

      - name: push client cointainer
        run: docker push jrodga1604/multi-client
      
      - name: push nginx cointainer
        run: docker push jrodga1604/multi-nginx
      
      - name: push server cointainer
        run: docker push jrodga1604/multi-server
      
      - name: push worker cointainer
        run: docker push jrodga1604/multi-worker
